# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FilePathField(default=None, match='/.+(\\.png$|\\.jpeg$|\\.jpg$)/', path='.'),
        ),
    ]
