# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20160512_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='articles-img'),
        ),
    ]
